// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: addrinfo.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Addrs [][]byte `protobuf:"bytes,2,rep,name=Addrs,proto3" json:"Addrs,omitempty"`
}

func (x *AddrInfo) Reset() {
	*x = AddrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_addrinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrInfo) ProtoMessage() {}

func (x *AddrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_addrinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrInfo.ProtoReflect.Descriptor instead.
func (*AddrInfo) Descriptor() ([]byte, []int) {
	return file_addrinfo_proto_rawDescGZIP(), []int{0}
}

func (x *AddrInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AddrInfo) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type AddrInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddrInfos []*AddrInfo `protobuf:"bytes,1,rep,name=addrInfos,proto3" json:"addrInfos,omitempty"`
}

func (x *AddrInfos) Reset() {
	*x = AddrInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_addrinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddrInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrInfos) ProtoMessage() {}

func (x *AddrInfos) ProtoReflect() protoreflect.Message {
	mi := &file_addrinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrInfos.ProtoReflect.Descriptor instead.
func (*AddrInfos) Descriptor() ([]byte, []int) {
	return file_addrinfo_proto_rawDescGZIP(), []int{1}
}

func (x *AddrInfos) GetAddrInfos() []*AddrInfo {
	if x != nil {
		return x.AddrInfos
	}
	return nil
}

var File_addrinfo_proto protoreflect.FileDescriptor

var file_addrinfo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x64, 0x64, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x30, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x14, 0x0a, 0x05, 0x41, 0x64, 0x64, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x05, 0x41, 0x64, 0x64, 0x72, 0x73, 0x22, 0x37, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x73, 0x12, 0x2a, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x42,
	0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_addrinfo_proto_rawDescOnce sync.Once
	file_addrinfo_proto_rawDescData = file_addrinfo_proto_rawDesc
)

func file_addrinfo_proto_rawDescGZIP() []byte {
	file_addrinfo_proto_rawDescOnce.Do(func() {
		file_addrinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_addrinfo_proto_rawDescData)
	})
	return file_addrinfo_proto_rawDescData
}

var file_addrinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_addrinfo_proto_goTypes = []interface{}{
	(*AddrInfo)(nil),  // 0: pb.AddrInfo
	(*AddrInfos)(nil), // 1: pb.AddrInfos
}
var file_addrinfo_proto_depIdxs = []int32{
	0, // 0: pb.AddrInfos.addrInfos:type_name -> pb.AddrInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_addrinfo_proto_init() }
func file_addrinfo_proto_init() {
	if File_addrinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_addrinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_addrinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddrInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_addrinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_addrinfo_proto_goTypes,
		DependencyIndexes: file_addrinfo_proto_depIdxs,
		MessageInfos:      file_addrinfo_proto_msgTypes,
	}.Build()
	File_addrinfo_proto = out.File
	file_addrinfo_proto_rawDesc = nil
	file_addrinfo_proto_goTypes = nil
	file_addrinfo_proto_depIdxs = nil
}
